repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - { name: "typecheck", id: pyright }
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - { name: "lint", id: ruff-check, args: [--fix] }
      - { name: "format", id: ruff-format }
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - { name: "lock", id: uv-lock }
      - { name: "requirements", id: uv-export }
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - { id: gitlint }
